config/routes.rb
Rails.application.routes.draw do
  resources :user_workflow_statuses
  resources :workflows do
    resources :workflow_states
  end
    resources :workflow_states do
      resources :workflow_events
    end

    resources :workflow_events
    resources :workflow_events do
      resources :transitions do
        member do
          get 'set_state'
        end
      end
    end

end

app/models/transition.rb
class Transition
  include Mongoid::Document
  include Mongoid::Timestamps
  
  belongs_to :workflow_state
  belongs_to :workflow_event
end

app/controllers/transitions_controller.rb
class TransitionsController < ApplicationController
  before_action :set_transition, only: [:show, :edit, :update, :destroy, :set_state]
  before_action :set_workflow_event

  # GET /transitions
  # GET /transitions.json
  def index
    @transitions = @workflow_event.transition.to_a
  end

  # GET /transitions/1
  # GET /transitions/1.json
  def show
    respond_to do |format|
      format.html {}
      format.json { render json:  @transition}
    end
  end

  # GET /transitions/new
  def new
    @transition = @workflow_event.build_transition
  end

  # GET /transitions/1/edit
  def edit
  end

  # POST /transitions
  # POST /transitions.json
  def create
    @transition = @workflow_event.build_transition(transition_params)

    respond_to do |format|
      if @transition.save
        format.html { redirect_to workflow_event_transition_path(@workflow_event, @transition), notice: 'Transition was successfully created.' }
        format.json { render :show, status: :created, location: @transition }
      else
        format.html { render :new }
        format.json { render json: @transition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transitions/1
  # PATCH/PUT /transitions/1.json
  def update
    respond_to do |format|
      if @transition.update(transition_params)
        format.html { redirect_to workflow_event_transition_path(@workflow_event, @transition), notice: 'Transition was successfully updated.' }
        format.json { render :show, status: :ok, location: @transition }
      else
        format.html { render :edit }
        format.json { render json: @transition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transitions/1
  # DELETE /transitions/1.json
  def destroy
    @transition.destroy
    respond_to do |format|
      format.html { redirect_to workflow_events_transitions_url, notice: 'Transition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_state
    uws = UserWorkflowStatus.find_or_create_by(user_id: current_user.id)
    uws.workflow_state = @transition.workflow_state
    uws.workflow = @transition.workflow_state.workflow
    uws.save

    respond_to do |format|
      format.json { render json:  @transition.workflow_state }
    end

   
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transition
      @transition = Transition.find(params[:id])
    end

    def set_workflow_event
      @workflow_event = WorkflowEvent.find(params[:workflow_event_id])
      @workflow = @workflow_event.workflow_state.workflow
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transition_params
      params.require(:transition).permit(:workflow_state_id, :workflow_event_id)
    end
end

app/helpers/transitions_helper.rb
module TransitionsHelper
end

app/views/transitions/_form.html.erb
<%= form_for([@workflow_event, @transition]) do |f| %>
  <% if @transition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transition.errors.count, "error") %> prohibited this transition from being saved:</h2>

      <ul>
      <% @transition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <h4>Workflow event: <%= @workflow_event.event %></h4>
    <%= f.hidden_field :workflow_event_id, value: @workflow_event.id %>
    <%= f.select(:workflow_state_id, @workflow.workflow_states.collect {|u| [u.state, u.id]}, :prompt => 'Select') %>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transitions/edit.html.erb
<h1>Editing Transition</h1>

<%= render 'form' %>

<%= link_to 'Show', workflow_event_transition_path(@workflow_event , @transition) %> |
<%= link_to 'Back', workflow_event_transitions_path(@workflow_event) %>

app/views/transitions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Transitions</h1>

<table>
  <thead>
    <tr>
      <th>Workflow state</th>
      <th>Workflow event</th>
      <th>Transition state</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transitions.each do |transition| %>
      <tr>
        <td><%= transition.workflow_event.workflow_state.state %></td>
        <td><%= transition.workflow_event.event %></td>
        <td><%= transition.workflow_state.state %></td>
        <td><%= link_to 'Show', workflow_event_transition_path(@workflow_event , transition) %></td>
        <td><%= link_to 'Edit', edit_workflow_event_transition_path(@workflow_event,transition) %></td>
        <td><%= link_to 'Destroy', workflow_event_transition_path(@workflow_event , transition), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transition', new_workflow_event_transition_path(@workflow_event) %>
<%= link_to 'Back', workflow_state_workflow_event_path(@workflow_event.workflow_state, @workflow_event) %>

app/views/transitions/new.html.erb
<h1>New Transition</h1>

<%= render 'form' %>

<%= link_to 'Back', workflow_event_transitions_path(@workflow_event) %>

app/views/transitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Workflow state:</strong>
  <%= @transition.workflow_state.state %>
</p>

<p>
  <strong>Workflow event:</strong>
  <%= @transition.workflow_event.event %>
</p>

<%= link_to 'Edit', edit_workflow_event_transition_path(@workflow_event, @transition) %> |
<%= link_to 'Back', workflow_event_transitions_path(@workflow_event) %>