config/routes.rb
Rails.application.routes.draw do
  resources :user_workflow_statuses
  resources :workflows do
    resources :workflow_states
  end
    resources :workflow_states do
      resources :workflow_events
    end

    resources :workflow_events
    resources :workflow_events do
      resources :transitions do
        member do
          get 'set_state'
        end
      end
    end

end

app/models/workflow.rb
class Workflow
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :workflow_states
  has_one :user_workflow_status
  

  field :name, type: String
  field :description, type: String
end

app/controllers/workflows_controller.rb
class WorkflowsController < ApplicationController
  before_action :set_workflow, only: [:show, :edit, :update, :destroy]

  # GET /workflows
  # GET /workflows.json
  def index
    @workflows = Workflow.all
    respond_to do |format|
        format.html {}
        format.json { render json: @workflows }
    end
  end

  # GET /workflows/1
  # GET /workflows/1.json
  def show
    respond_to do |format|
        format.html {}
        format.json { render json: @workflow }
    end
  end

  # GET /workflows/new
  def new
    @workflow = Workflow.new
  end

  # GET /workflows/1/edit
  def edit
  end

  # POST /workflows
  # POST /workflows.json
  def create
    @workflow = Workflow.new(workflow_params)

    respond_to do |format|
      if @workflow.save
        format.html { redirect_to @workflow, notice: 'Workflow was successfully created.' }
        format.json { render :show, status: :created, location: @workflow }
      else
        format.html { render :new }
        format.json { render json: @workflow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workflows/1
  # PATCH/PUT /workflows/1.json
  def update
    respond_to do |format|
      if @workflow.update(workflow_params)
        format.html { redirect_to @workflow, notice: 'Workflow was successfully updated.' }
        format.json { render :show, status: :ok, location: @workflow }
      else
        format.html { render :edit }
        format.json { render json: @workflow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workflows/1
  # DELETE /workflows/1.json
  def destroy
    @workflow.destroy
    respond_to do |format|
      format.html { redirect_to workflows_url, notice: 'Workflow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workflow
      @workflow = Workflow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workflow_params
      params.require(:workflow).permit(:name, :description)
    end
end

app/helpers/workflows_helper.rb
module WorkflowsHelper
end

app/views/workflows/_form.html.erb
<%= form_for(@workflow) do |f| %>
  <% if @workflow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workflow.errors.count, "error") %> prohibited this workflow from being saved:</h2>

      <ul>
      <% @workflow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workflows/edit.html.erb
<h1>Editing Workflow</h1>

<%= render 'form' %>

<%= link_to 'Show', @workflow %> |
<%= link_to 'Back', workflows_path %>

app/views/workflows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Workflows</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workflows.each do |workflow| %>
      <tr>
        <td><%= workflow.name %></td>
        <td><%= workflow.description %></td>
        <td><%= link_to 'Show', workflow %></td>
        <td><%= link_to 'Edit', edit_workflow_path(workflow) %></td>
        <td><%= link_to 'Destroy', workflow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workflow', new_workflow_path %>

app/views/workflows/new.html.erb
<h1>New Workflow</h1>

<%= render 'form' %>

<%= link_to 'Back', workflows_path %>

app/views/workflows/show.html.erb
<h2 style="margin-bottom:0px;">Workflow</h2>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @workflow.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @workflow.description %>
</p>

<h5 style="margin-bottom:0px;">Workflow state</h5>
		<table style="margin-left:20px;">
			<tbody>
	<% @workflow.workflow_states.each do |ws| %>
				<tr>
				<td><%= ws.state %></td>
				 <td><%= link_to 'Show', workflow_workflow_state_path(@workflow, ws) %></td>
				<td><%= link_to 'Edit', edit_workflow_workflow_state_path(@workflow, ws) %></td>
		        <td><%= link_to 'Destroy', workflow_workflow_state_path(@workflow, ws) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
		        </tr>
	<% end %>
			</tbody>
		</table>


<%= link_to 'Edit', edit_workflow_path(@workflow) %> |
<%= link_to 'Back', workflows_path %>
<%= link_to 'Create state', new_workflow_workflow_state_path(@workflow) %>