config/routes.rb
Rails.application.routes.draw do
  resources :user_workflow_statuses
  resources :workflows do
    resources :workflow_states
  end
    resources :workflow_states do
      resources :workflow_events
    end

    resources :workflow_events
    resources :workflow_events do
      resources :transitions do
        member do
          get 'set_state'
        end
      end
    end

end

app/models/workflow_event.rb
class WorkflowEvent
  include Mongoid::Document
  include Mongoid::Timestamps

  has_one :transition

  field :event, type: String
  belongs_to :workflow_state
end

app/controllers/workflow_events_controller.rb
class WorkflowEventsController < ApplicationController
  before_action :set_workflow_event, only: [:show, :edit, :update, :destroy]
  before_action :set_workflow_state


  # GET /workflow_events
  # GET /workflow_events.json
  def index
    @workflow_events = @workflow_state.workflow_events
  end

  # GET /workflow_events/1
  # GET /workflow_events/1.json
  def show
    @transition = @workflow_event.transition
    respond_to do |format|
        format.html {}
        format.json { render json: @workflow_event }
    end
  end

  # GET /workflow_events/new
  def new
    @workflow_event = @workflow_state.workflow_events.build
  end

  # GET /workflow_events/1/edit
  def edit
  end

  # POST /workflow_events
  # POST /workflow_events.json
  def create
    @workflow_event = WorkflowEvent.new(workflow_event_params)

    respond_to do |format|
      if @workflow_event.save
        format.html { redirect_to workflow_state_workflow_event_path(@workflow_state, @workflow_event), notice: 'Workflow event was successfully created.' }
        format.json { render :show, status: :created, location: @workflow_event }
      else
        format.html { render :new }
        format.json { render json: @workflow_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workflow_events/1
  # PATCH/PUT /workflow_events/1.json
  def update
    respond_to do |format|
      if @workflow_event.update(workflow_event_params)
        format.html { redirect_to workflow_state_workflow_event_path(@workflow_state, @workflow_event), notice: 'Workflow event was successfully updated.' }
        format.json { render :show, status: :ok, location: @workflow_event }
      else
        format.html { render :edit }
        format.json { render json: @workflow_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workflow_events/1
  # DELETE /workflow_events/1.json
  def destroy
    @workflow_event.destroy
    respond_to do |format|
      format.html { redirect_to workflow_state_workflow_events_path, notice: 'Workflow event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workflow_event
      @workflow_event = WorkflowEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workflow_event_params
      params.require(:workflow_event).permit(:workflow_state_id, :event, :id)
    end

    def set_workflow_state
      @workflow_state = WorkflowState.find(params[:workflow_state_id])
    end
end

app/helpers/workflow_events_helper.rb
module WorkflowEventsHelper
end

app/views/workflow_events/_form.html.erb
<%= form_for([@workflow_state, @workflow_event]) do |f| %>
  <% if @workflow_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workflow_event.errors.count, "error") %> prohibited this workflow_event from being saved:</h2>

      <ul>
      <% @workflow_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :workflow_state_id %>
  <div class="field">
    <%= f.label :event %><br>
    <%= f.text_field :event %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workflow_events/edit.html.erb
<h1>Editing Workflow Event</h1>

<%= render 'form' %>

<%= link_to 'Show', workflow_state_workflow_event_path(@workflow_state, @workflow_event) %> |
<%= link_to 'Back', workflow_state_workflow_events_path %>

app/views/workflow_events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Workflow Events</h1>
<h4>Workflow state: <%= @workflow_state.state %></h4>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workflow_events.each do |workflow_event| %>
      <tr>
        <td><%= workflow_event.event %></td>
        <td><%= link_to 'Show', workflow_state_workflow_event_path(@workflow_state, workflow_event) %></td>
        <td><%= link_to 'Edit', edit_workflow_state_workflow_event_path(@workflow_state, workflow_event) %></td>
        <td><%= link_to 'Destroy', workflow_state_workflow_event_path(@workflow_state, workflow_event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workflow event', new_workflow_state_workflow_event_path(@workflow_state) %>
<%= link_to 'Back', workflow_workflow_states_path(@workflow_state.workflow) %>

app/views/workflow_events/new.html.erb
<h1>New Workflow Event</h1>

<h3>Workflow state: <%= @workflow_state.state %> </h3>

<%= render 'form' %>

<%= link_to 'Back', workflow_state_workflow_events_path %>

app/views/workflow_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Workflow state:</strong>
  <%= @workflow_event.workflow_state.state %>
</p>

<p>
  <strong>Event:</strong>
  <%= @workflow_event.event %>
<%= link_to 'Edit', edit_workflow_state_workflow_event_path(@workflow_state, @workflow_event) %>

</p>

<% if @transition.present? %>
<table>
  <thead>
    <tr>
      <th>Workflow state</th>
      <th>Workflow event</th>
      <th>Transition state</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @transition.workflow_event.workflow_state.state %></td>
        <td><%= @transition.workflow_event.event %></td>
        <td><%= @transition.workflow_state.state %></td>
        <!-- <td><%= link_to 'Show', workflow_event_transition_path(@workflow_event , @transition) %></td> -->
        <td><%= link_to 'Edit', edit_workflow_event_transition_path(@workflow_event,@transition) %></td>
        <td><%= link_to 'Destroy', workflow_event_transition_path(@workflow_event , @transition), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  </tbody>
</table>
<% else %>
	<%= link_to 'set Transition', new_workflow_event_transition_path(@workflow_event) %>
 |
<% end %>
<%= link_to 'Back', workflow_state_workflow_events_path %>