config/routes.rb
Rails.application.routes.draw do
  resources :user_workflow_statuses
  resources :workflows do
    resources :workflow_states
  end
    resources :workflow_states do
      resources :workflow_events
    end

    resources :workflow_events
    resources :workflow_events do
      resources :transitions do
        member do
          get 'set_state'
        end
      end
    end

end

app/models/workflow_state.rb
class WorkflowState
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :workflow_events
  has_one :user_workflow_status
  

  field :state, type: String
  field :content, type: String

  belongs_to :workflow
end

app/controllers/workflow_states_controller.rb
class WorkflowStatesController < ApplicationController
  before_action :set_workflow_state, only: [:show, :edit, :update, :destroy]
  before_action :set_workflow
  # GET /workflow_states
  # GET /workflow_states.json
  def index
    @workflow_states = @workflow.workflow_states
  end

  # GET /workflow_states/1
  # GET /workflow_states/1.json
  def show
    respond_to do |format|
        format.html {}
        format.json { render json: @workflow_state }
    end
  end

  # GET /workflow_states/new
  def new
    @workflow_state = @workflow.workflow_states.build
  end

  # GET /workflow_states/1/edit
  def edit
  end

  # POST /workflow_states
  # POST /workflow_states.json
  def create
    @workflow_state = @workflow.workflow_states.build(workflow_state_params)
    respond_to do |format|
      if  @workflow_state.save
        format.html { redirect_to workflow_workflow_state_path(@workflow, @workflow_state), notice: 'Workflow state was successfully created.' }
        format.json { render :show, status: :created, location: @workflow_state }
      else
        format.html { render :new }
        format.json { render json: @workflow_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workflow_states/1
  # PATCH/PUT /workflow_states/1.json
  def update
    respond_to do |format|
      if @workflow_state.update(workflow_state_params)
        format.html { redirect_to workflow_workflow_state_path(@workflow, @workflow_state), notice: 'Workflow state was successfully updated.' }
        format.json { render :show, status: :ok, location: @workflow_state }
      else
        format.html { render :edit }
        format.json { render json: @workflow_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workflow_states/1
  # DELETE /workflow_states/1.json
  def destroy
    @workflow_state.destroy
    respond_to do |format|
      format.html { redirect_to workflow_states_url, notice: 'Workflow state was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workflow_state
      @workflow_state = WorkflowState.find(params[:id])
    end

    def set_workflow
      @workflow = Workflow.find(params[:workflow_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workflow_state_params
      params.require(:workflow_state).permit(:workflow_id, :state, :content, :id)
    end
end

app/helpers/workflow_states_helper.rb
module WorkflowStatesHelper
end

app/views/workflow_states/_form.html.erb
<%= form_for([@workflow, @workflow_state]) do |f| %>
  <% if @workflow_state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workflow_state.errors.count, "error") %> prohibited this workflow_state from being saved:</h2>

      <ul>
      <% @workflow_state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :workflow_id, value: @workflow.id  %>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workflow_states/edit.html.erb
<h1>Editing Workflow State</h1>

<%= render 'form' %>

<%= link_to 'Show', @workflow_state %> |
<%= link_to 'Back', workflow_states_path %>

app/views/workflow_states/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Workflow States</h1>

<h4>Workflow: <%= @workflow.name %></h4>
<table>
  <thead>
    <tr>
      <th>State</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workflow_states.each do |workflow_state| %>
      <tr>
        <td><%= workflow_state.state %></td>
        <td><%= workflow_state.content %></td>
        <td><%= link_to 'Show', workflow_workflow_state_path(@workflow, workflow_state) %></td>
        <td><%= link_to 'Edit', edit_workflow_workflow_state_path(@workflow, workflow_state) %></td>
        <td><%= link_to 'Destroy', workflow_workflow_state_path(@workflow, workflow_state) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workflow state', new_workflow_workflow_state_path(@workflow) %>
<%= link_to 'Back', workflows_path(@workflow) %>

app/views/workflow_states/new.html.erb
<h1>New Workflow State</h1>

<%= render 'form' %>

<%= link_to 'Back', workflow_workflow_states_path(@workflow) %>

app/views/workflow_states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Workflow:</strong>
  <%= @workflow_state.workflow.name %>
</p>

<p>
  <strong>State:</strong>
  <%= @workflow_state.state %>
</p>
<p>
  <strong>Content:</strong>
  <%= @workflow_state.content %>
</p>

<h5 style="margin-bottom:0px;">Workflow Events</h5>
		<table style="margin-left:20px;">
			<tbody>
	<% @workflow_state.workflow_events.each do |workflow_event| %>
				<tr>
				<td><%= workflow_event.event %></td>
				 <td><%= link_to 'Show', workflow_state_workflow_event_path(@workflow_state, workflow_event) %></td>
				<td><%= link_to 'Edit', edit_workflow_state_workflow_event_path(@workflow_state, workflow_event) %></td>
		        <td><%= link_to 'Destroy', workflow_state_workflow_event_path(@workflow_state, workflow_event) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
		        </tr>
	<% end %>
			</tbody>
		</table>

<%= link_to 'Edit', edit_workflow_workflow_state_path(@workflow, @workflow_state) %> |
<%= link_to 'Back', workflow_workflow_states_path %>
<%= link_to 'Create event', new_workflow_state_workflow_event_path(@workflow_state) %>